# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token f0035bf72752f587b2aedda46bfaa180ecf6b8f0

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token f0035bf72752f587b2aedda46bfaa180ecf6b8f0

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token 8f3d337fe14f3e3e5bc6b224c681ddfe0c83bfd7
###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-10-01
Content-Type: application/json
Authorization: Token 8f3d337fe14f3e3e5bc6b224c681ddfe0c83bfd7

###

DELETE {{baseUrl}}/advertisements/24/
Authorization: Token 8f3d337fe14f3e3e5bc6b224c681ddfe0c83bfd7

###

GET {{baseUrl}}/advertisements/?status=CLOSED
Authorization: Token 8f3d337fe14f3e3e5bc6b224c681ddfe0c83bfd7